version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "<-- RUNTIME EXECUTION -->"
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - yum update -y
      - yum install -y jq


  pre_build:
    commands:
      - echo "pre build stage completed"
      - echo "PyLint Started"
      - pylint rent_my_ride/**/*.py || true
      - echo "pre build stage completed - PyLint Completed!!"


artifacts:
  files:
    - '**/*'
